version: '3'

services: 
    web:
        build: ./dj_app
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./dj_app/:/usr/src/dj_app
        ports:
            - 8000:8000
        env_file:
            - ./.env.dev
        depends_on: 
            - db
    
    db:
        image: postgres:12.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment: 
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=testdocker
volumes:
    postgres_data:


